{{- $fullName := include "dftbackend.fullname" . }}
{{- $labels := include "dftbackend.labels" . | nindent 4 }}
{{- $gitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- $dftbackendEndpoints := .Values.dftbackend.endpoints }}
{{- $namespace := .Release.Namespace }}
{{- range .Values.ingresses }}
{{- if and .enabled .endpoints }}
{{- $ingressName := printf "%s-%s" $fullName .hostname }}
---
{{- if semverCompare ">=1.19-0" $gitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $gitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  namespace: {{ $namespace | default "default" | quote }}
  labels:
    {{- $labels | nindent 2 }}
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" $gitVersion) }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .hostname }}
  {{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ .hostname }}
      {{- if .tls.secretName }}
      secretName: {{ .tls.secretName }}
      {{- else }}
      secretName: {{ $ingressName }}-tls
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .hostname }}
      http:
        paths:
          {{- $ingressdftbackendEndpoints := .endpoints }}
          {{- range  $name, $mapping := $dftbackendEndpoints }}
          {{- if (has $name $ingressdftbackendEndpoints) }}
          - path: {{ $mapping.path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $gitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $mapping.port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $mapping.port }}
              {{- end }}
        {{- end }}
  {{- end }}
  {{- end }}
{{- end }}{{- /* end: if .enabled */}}
{{- end }}{{- /* end: range .Values.ingresses */}}
