apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "omejdn-server.fullname" . }}
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
