apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daps-pv-claim
  labels:
    app: daps
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
